### ISSUE TITLE
Icon CSS

### ISSUE THREAD

**Issue by zeusbangayan** [MohammadYounes/rtlcss#105]
how can I make this work?
```scss
.icon-chevron-right:before {
    content: "\e91f" #{"/*rtl:\e91e*/"};
}
```

**Comment by jjlharrison** [comment]
@zeusbangayan: The following works, you can try it using the [RTLCSS Playground](http://rtlcss.com/playground/). If it isn't working for you it's probably because your CSS Preprocessor (e.g. LESS or SASS) is stripping it out.

```css
.icon-chevron-right:before {
    content: \e91f /*rtl:\e91e*/;
}
```

**Comment by MohammadYounes** [comment]
@zeusbangayan I guess you are using `node-sass` ? It seems it has a special handling for Unicode characters. It does strip out comments inside `content` declaration even if interpolated.

As a work around you can use [`raw` directive](http://rtlcss.com/learn/usage-guide/control-directives/#raw), but be aware, some minifiers remove duplicate declarations:

```scss
.icon-chevron-right:before {
    content: "\e91f";
   /*!rtl:raw:
    content: "\e91e";
   */
}
```

**Comment by zeusbangayan** [comment]
im currently using gulp. i found this https://www.npmjs.com/package/gulp-rtlcss. let me try first your recos. thanks @MohammadYounes and @jjlharrison

**Comment by zeusbangayan** [comment]
fixed it using #{"/*rtl:'\e91f'*/"}

thanks!

**Comment by MohammadYounes** [comment]
Ah, It wasn't clear that this was your problem. The one I described applies to a webpack build using node-sass.

Thanks for the feedback!

**Comment by zeusbangayan** [comment]
last question, how do you switch :before and :after? iwas trying this but to no avail

	/*!rtl:raw:
		&:after {
			font-family: $nav-breadcrumbs-divider-font;
			content: $nav-breadcrumbs-divider;
			color: $nav-breadcrumbs-divider-color;
		}
	   */

/*!rtl:remove*/
		&:before {
			font-family: $nav-breadcrumbs-divider-font;
			content: $nav-breadcrumbs-divider;
			color: $nav-breadcrumbs-divider-color;
		}

**Comment by MohammadYounes** [comment]
Not sure why you need to that! Anyhow, you need to separate them to maintain comment position in the output css (without using `&`):

```scss
/*!rtl:raw:
  .example:after {
      font-family: $nav-breadcrumbs-divider-font;
      content: $nav-breadcrumbs-divider;
      color: $nav-breadcrumbs-divider-color;
   }
*/
/*!rtl:remove*/
  .example:before {
    font-family: $nav-breadcrumbs-divider-font;
    content: $nav-breadcrumbs-divider;
    color: $nav-breadcrumbs-divider-color;
}
```
