### ISSUE TITLE
Imported CSS files 

### ISSUE THREAD

**Issue by hiahmedsaad** [MohammadYounes/rtlcss#108]
Hello ,
how could i  to do this ?

input
@import url("example.css"); 

output 
@import url("example-rtl.css");

**Comment by jjlharrison** [comment]
You could do:

```css
/*rtl:remove*/ @import url("example.css");
/*rtl:raw:@import url("example-rtl.css")*/
```

**Comment by hiahmedsaad** [comment]
Thanks 
remove and raw works Great.
i don't familiar with processUrls option method. i am just use  this  
$ rtlcss style.css style-rtl.css

**Comment by MohammadYounes** [comment]
In addition to the [`raw` directive](http://rtlcss.com/learn/usage-guide/control-directives/#raw) suggested by @jjlharrison. You can have this applied to all imports in your CSS using a [string map](http://rtlcss.com/learn/usage-guide/string-map/). For example:

```css
/*rtl:options:
{
  "processUrls": { "atrule": true, "decl": false },
  "stringMap": [
   {
       "name": "import-rtl-stylesheet",
       "priority": 10,
       "exclusive": true,
       "search": ".css",
       "replace": "-rtl.css",
       "options": {
           "scope": "url",
            "ignoreCase": false
        }
      }
    ]
}*/

@import url("example.css");


.example {
  direction: ltr;
}
```

Gives you:
```css
@import url("example-rtl.css");


.example {
  direction: rtl;
}
```

Moreover, You can move the options into a [configuration file](http://rtlcss.com/learn/usage-guide/cli/#config) as mentioned in the [CLI documentation](http://rtlcss.com/learn/usage-guide/cli).

**rtlcss.config.json**

```json
{
  "options": {
    "processUrls": {
      "atrule": true,
      "decl": false
    },
    "stringMap": [
      {
        "name": "import-rtl-stylesheet",
        "priority": 10,
        "exclusive": true,
        "search": ".css",
        "replace": "-rtl.css",
        "options": {
          "scope": "url",
          "ignoreCase": false
        }
      }
    ]
  }
}
```
Then 
```bash
$ rtlcss  -c rtlcss.config.json style.css style-rtl.css
```

Thanks!
