### ISSUE TITLE
Option to generate CSS supporting both layouts

### ISSUE THREAD

**Issue by elsassph** [MohammadYounes/rtlcss#140]
Would it be possible to generate RTL code as overrides?
e.g.
```css
.something {
  display: block;
  margin-left: 20px;
}
```
becomes:
```css
.something {
  display: block;
}
html[dir="ltr"] .something {
  margin-left: 20px;
}
html[dir="rlt"] .something {
   margin-right: 20px;
}
```
