### ISSUE TITLE
Prevent automatic conversion

### ISSUE THREAD

**Issue by dNitro** [MohammadYounes/rtlcss#143]
Is there any option to prevent automatic conversion and do it manually through directives: i.e  `/*rtl: ... */` ?!!!
Sometimes rtl styles are much the same as ltr but there is needed just a rule or two to be changed or added in rtl one; for example in the whole following ltr stylesheet, only **one specific rule** needs to be changed to make it rtl ready: `text-align`:
```css
a { ... }
b { ... }
.content {
  text-align: left;
}
d { ... }
e { ... }
```
Already if we process this stylesheet with rtlcss it will make text right aligned: `text-align: right` but it would also change all other rules which have direction! whereas we needed them untouched! how could someone achieve that?

Having an option to prevent automatic conversion: `auto: false`, it is possible to have more fine-grained control over conversions and add them manually using directives:
( disable automatic conversion and using `rename` directive`: )
```css
a { ... }
b { ... }
.content {
  text-align: left /*rtl:right*/;
}
d { ... }
e { ... }
```
