### ISSUE TITLE
invert background-position as part of animation

### ISSUE THREAD

**Issue by felixmosh** [MohammadYounes/rtlcss#152]
Semantic-UI has a placeholder animation that moves background horizontally.

```css
@keyframes placeholderShimmer {
  0% {
    background-position: -1200px 0;
  }

  100% {
    background-position: 1200px 0;
  }
}
```

**Comment by MohammadYounes** [comment]
`background-position` expressed in length units is flipped once you enable `useCalc` [option](https://rtlcss.com/learn/usage-guide/options/).

**Comment by nex3** [comment]
Why does this use `calc()` to flip rather than compiling to

```css
@keyframes placeholderShimmer {
  0% {
    background-position: right -1200px 0;
  }

  100% {
    background-position: right 1200px 0;
  }
}
```

...which doesn't require `calc()` and thus doesn't need to be locked behind the `useCalc` option?

**Comment by MohammadYounes** [comment]
@nex3  Because this is invalid. **3-value syntax** is composed of two keywords and one offset (length or percentage).

see https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

**Comment by nex3** [comment]
Haha, good point. But this is valid:

```css
@keyframes placeholderShimmer {
  0% {
    background-position: right -1200px top 0;
  }

  100% {
    background-position: right 1200px top 0;
  }
}
```

In other words, according to the spec, `background-position: X Y` is equivalent to `background-position: left X top Y` (where `X` and `Y` are numbers), but the latter is flipped without `useCalc` and the former is not.
