### ISSUE TITLE
Bidirectional output mode

### ISSUE THREAD

**Issue by nex3** [MohammadYounes/rtlcss#153]
I work on the CSS infrastructure team at Google, and we're considering adopting RTLCSS as the standard for language conversion. However, one feature we'd really like to see that doesn't exist yet is the ability to emit a single output file that supports both LTR and RTL browsers.

Specifically, we'd like to be able to specify a pair of parent selectors (say `[dir="ltr"]` and `[dir="rtl"]`, or `:host-context([dir="ltr"])` and `:host-context([dir="rtl"])`) and have RTLCSS copy the subset of each ruleset that contains convertible rules into new rulesets nested under those selectors. So for example, with `{bidi: {ltr: '[dir="ltr"]', rtl: '[dir="rtl"]'}}`:

```css
.example {
   margin: 0;
   padding: 1em 2em .5em 1em;
}
```

would compile to:

```css
.example {
   margin: 0;
}

[dir="ltr"] .example {
   padding: 1em 2em .5em 1em;
}

[dir="rtl"] .example {
  padding: 1em 1em .5em 2em;
}
```

Is this a feature you'd be open to adding?
