### ISSUE TITLE
String map config doesn't work for multiple rules

### ISSUE THREAD

**Issue by fritzmonkey** [MohammadYounes/rtlcss#160]
When supplying a stringMap option, it is ignored if the block contains something else that is being string mapped.

Input:
```
/*rtl:begin:options:{
  "autoRename": true,
  "stringMap": [{
    "name": "after-replace",
    "search": "before",
    "replace": "after"
  }]
} */
.btn:before {
  margin-right: 2px;
}
/*rtl:end:options*/
```

Output:
```
.btn:before {
  margin-left: 2px;
}
```

Expected Output:
```
.btn:after {
  margin-left: 2px;
}
```

Only the default string map is applied, no matter what. The priority has no impact, and trying to overwrite the default `left-right` doesn't seem to work either.

**Comment by MohammadYounes** [comment]
Since your example contains directional properties, No renaming will occur.  

>  [[docs](https://rtlcss.com/learn/usage-guide/options/)] `autoRename` applies to CSS rules containing no directional properties.

You can force renaming of such rules by using a [`rename` control directive](https://rtlcss.com/learn/usage-guide/control-directives/#rename).

```css
/*rtl:begin:options:{
  "autoRename": true,
  "stringMap": [{
    "name": "after-replace",
    "search": "before",
    "replace": "after"
  }]
} */
/*rtl:rename*/
.btn:before {
  margin-right: 2px;
}
/*rtl:end:options*/
```
