### ISSUE TITLE
Provide a more semantic way of specifying RTL-only styles

### ISSUE THREAD

**Issue by nex3** [MohammadYounes/rtlcss#164]
Currently, if an author wants to add styles only for RTL stylesheets, they have to include it in `/*rtl:raw:...*/` comments. CSS that's locked in a comment has a number of downsides: it can't be syntax highlighted, it can't be linted, and it's not processed by earlier post-processing steps like Autoprefixer. It would be nice to have a more CSS-y way of indicating that a style is only intended for the RTL stylesheet.

I suggest doing this by treating style rules whose selectors contain `:dir(rtl)` or `:dir(ltr)` specially, since in CSS those already indicate "these styles only apply in RTL or LTR mode." Specifically:

* Remove `:dir(rtl)` from selectors, so that for example `:dir(rtl) .foo { ... }` or `.foo:dir(rtl)` would both become `.foo { ... }`, and `.foo :dir(rtl) { ... }` would become `.foo * { ... }`.

* Delete selectors that contain `:dir(ltr)` and style rules whose selectors are all deleted this way.

* In [bidi mode](https://github.com/MohammadYounes/rtlcss/issues/153), translate selectors that use `:dir(rtl)` or `:dir(ltr)` to selectors that use the given parent selectors instead. This would allow authors to write modern CSS with `:dir(rtl)`/`:dir(ltr)` but have it compile to something compatible with more browsers.

It would be especially cool if this had another LTR mode that did the reverse, removing `:dir(ltr)` from selectors and deleting selectors that contained `:dir(rtl)` entirely.

**Comment by MohammadYounes** [comment]
@nex3 The downsides you mentioned are all valid. However, The main reason behind directives is to handle edge cases. This also applies to the `/*rtl:raw...*/`, It's intended to write a tiny portion of CSS that need not to exist in the LTR version. For a CSS that should remain unchanged in both LTR/RTL, then `/*rtl:ignore*/` directive is the one to be used.

The major downside of modifying selectors is messing up their specificity. In my experience, I believe having a [complete separate file](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F) is the go-to solution, As changing the direction usually means a different language that will not need both LTR/RTL versions to be available at the same time.

To clarify things a bit more, CSS properties fall into 2 categories:

- **Direction Invariant**
  These has no significance in respect to horizontal direction from a definition perspective:
  -  Direction-Less, such as `vertical-align`, `color` ...`etc`. 
  -  Direction-Aware (these follow container direction), such as `flex`, `flex-direction`, `flex-wrap` and [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).

- **Direction Variant** (All [supported](https://rtlcss.com/learn/getting-started/why-rtlcss/#css-level-3) by rtlcss)
  These follow their own definition, regardless of the container direction. such as:

     `background`,`background-image`,`background-position`,`background-position-x`,`border-bottom-left-radius`,`border-bottom-right-radius`,`border-color`,`border-left`,`border-left-color`,`border-left-style`,`border-left-width`,`border-radius`,`border-right`,`border-right-color`,`border-right-style`,`border-right-width`,`border-style`,`border-top-left-radius`,`border-top-right-radius`,`border-width`,`box-shadow`,`clear`,`cursor`,`direction`,`float`,`left`,`margin`,`margin-left`,`margin-right`,`padding`,`padding-left`,`padding-right`,`right`,`text-align`,`text-shadow`,`transform`,`transform-origin`,`transition`,`transition-property`.


Now, in order to have a bidi version without breaking rules specificity, we must adhere to the following restrictions:

* Maintain CSS rules order.
* Prefix all **Variant Properties** even if they have no LTR/RTL difference: 
    * _**Neutral Prefix**_ (`:dir` or `[dir]`) for rules having no LTR/RTL difference.
    * _**Specific Prefix**_ (`:dir(ltr)`/`:dir(rtl)` or `[dir="ltr"]`/`[dir="rtl"]`) for rules having LTR/RTL difference.
* **Invariant Properties** can remain AS-IS with _**No Prefix**_.

For example, the following CSS:

> This is a hypothetical example just to [showcase](http://jsfiddle.net/ro5024sd/) how applying the bidi restrictions mentioned above will affect the output CSS.

```css
/*minified: 148 characters long.*/

body h1:last-child {
    color:blue;
    background:crimson;
    border:none;
    border-left:solid 10px black;    
}
div h1:first-child {
    color:red;
    border-right: solid 20px green
}
```

Will be converted to:

```css
/*minified: 666 characters long.*/

body h1:last-child {
  color:blue; /*Invariant*/
}
html[dir] body h1:last-child {
    background:crimson; /*Variant (LTR/RTL)*/
}
html[dir="ltr"] body h1:last-child {
  border-style: dashed dotted solid double; /*Variant (LTR)*/
  border-color: red green blue black; /*Variant (LTR)*/
}
html[dir="rtl"] body h1:last-child {
  border-style: dashed double solid dotted; /*Variant (RTL)*/
  border-color: red black blue green; /*Variant (RTL)*/
}
/*had to split to maintain rules order*/
html[dir] body h1:last-child { 
  border:none; /*Variant (LTR/RTL)*/
}
html[dir="ltr"] body h1:last-child{
  border-width: 1px 2px 3px 4px; /*Variant (LTR)*/
  border-left:solid 10px black; /*Variant (LTR)*/
}
html[dir="rtl"] body h1:last-child {
  border-width: 1px 4px 3px 2px; /*Variant (RTL)*/
  border-right:solid 10px black; /*Variant (RTL)*/
}


div h1:first-child {
  color:red; /*Invariant*/
}
html[dir="ltr"] div h1:first-child {
  border-right: solid 20px green; /*Variant (LTR)*/
}
html[dir="rtl"] div h1:first-child {
  border-left: solid 20px green; /*Variant (RTL)*/
}
```

Note how the bidi version is **4.5 times** larger than the original version.

That being said, Which will you choose,  a separate file per direction or one big bidi version ?
