### ISSUE TITLE
Override stringMap

### ISSUE THREAD

**Issue by elchininet** [MohammadYounes/rtlcss#165]
Hi @MohammadYounes,

First of all, thanks for your library, I replaced `CSSJanus` by it in one of my projects, because it is less buggy and more extendable.

I have a question that maybe is something intentional. I was trying to use my own `stringMap` and I noticed that no matter the `stringMap` used, the default `left-right` and `ltr-rtl` maps [are pushed into it](https://github.com/MohammadYounes/rtlcss/blob/6466fb744192f689e3afcc435ea8f4cec073e3ac/lib/config.js#L37). Take a look at [the next example](https://runkit.com/embed/wmgcyogua18y):

```css
.test1 {
    background: url("icons/ultra/chevronLeft.png");
}

.test2Left::before {
    content: "\\f30";
}

.test2Right::before {
    content: "\\f50";
}

.turtle-container {
    height: 100%;
    width: 100%;
}
```

```javascript
{
    autoRename: true,
    processUrls: true,
    greedy: true,
    stringMap: [
        {
            name: 'left-right',
            priority: 100,
            search: 'Left',
            replace: 'Right',
            options: { scope: '*', ignoreCase: false }
        }
    ]
}
```

Result:

```css
.test1 {
    background: url("icons/urtla/chevronRight.png");
}

.test2Right::before {
    content: "\f30";
}

.test2Left::before {
    content: "\f50";
}

.tultre-container {
    height: 100%;
    width: 100%;
} 
```

The url has been renamed from **ultra** to **urtla** and the selector from **turtle-container** to **tultre-container**. Is there any reason behind this? Why are enforced the default `ltr-rtl` ranaming rules?

The only workaround that I've found [is to replace the `ltr-rtl` map by an empty one](https://runkit.com/embed/rbtoc1au3ch1), so it will pass the condition to push it.

Thanks in advance
