### ISSUE TITLE
Difficulty converting

### ISSUE THREAD

**Issue by danialbakhtiari3884** [MohammadYounes/rtlcss#181]
How can the code be converted this way?

Example:

```
.test {
  width: 30%;
  margin-left: 30px;
}

```

The output should be shown like this.

```
.test {
  margin-left: inherit;
  margin-right: 30px;
}
```

**Comment by MohammadYounes** [comment]
@danialbakhtiari3884 You can use directives to customize the output:

```css
.test {
  /*rtl:remove*/
  width: 30%;
  margin-left: 30px /*rtl:inherit*/;
  /*rtl:raw:
  margin-right: 30px;
  */ 
}
```
