### ISSUE TITLE
v3.1.0: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by XhmikosR** [MohammadYounes/rtlcss#218]
https://github.com/twbs/bootstrap/pull/32960

v3.0.0 works fine.

```css
.dropdown-menu[style] {
  right: auto/* rtl:ignore */ !important;
}
```

Do we maybe need to change the directive to be after `!important`?

/CC @ffoodd
