### ISSUE TITLE
rtlcss in media query

### ISSUE THREAD

**Issue by iwfmp** [MohammadYounes/rtlcss#222]
seems to ignore when using media queries.

**Comment by MohammadYounes** [comment]
Can you provide an example ?

**Comment by iwfmp** [comment]
Just having a simple scss file:

`css
.popup {
  position: fixed;

  @include mq($until: tablet) {
    bottom: 15px;
    left: 15px;
  }
  @include mq(tablet) {
    bottom: 30px;
    right: 30px;
  }
}
`

rtlcss doesn't see the left/right rules under the media queries. In the delta created of the changes, the media query part is missing.

**Comment by MohammadYounes** [comment]
RTLCSS works on CSS output, can you provide a CSS example presenting the issue ?

**Comment by iwfmp** [comment]
having this css:

```css
.side-nav {
    right: 2vw;
    @include mq(desktop) { right: 5vw; }
}
```

is giving me this output (using the onlyDiff option):

```css
.side-nav {
    left: 2vw
}
```
