### ISSUE TITLE
adding zero opposite margin when switching auto margin

### ISSUE THREAD

**Issue by TheTBO** [MohammadYounes/rtlcss#225]
When switching an auto margin a 0 margin added in the opposite direction when using bootstrap scss.

example output:
 ```css
[dir="rtl"] .ms-lg-auto {
    margin-left: 0 !important;
    margin-right: auto !important;
  }
```

expected output:
```css
[dir="rtl"] .ms-lg-auto {
    margin-right: auto !important;
  }
```

Edit:
* I'm using override mode trying to generate a single RTL css file.
* I'm using webpack, postcss-loader, postcss-rtlcss
