### ISSUE TITLE
Flip env(safe-area-inset-*)

### ISSUE THREAD

**Issue by nex3** [MohammadYounes/rtlcss#231]
I'd expect RTLCSS to flip `env(safe-area-inset-left)` to `env(safe-area-inset-right)`, and vice versa. While these are likely to be the same on most devices, that's not guaranteed, so being able to flip them could be important for broad device compatibility.

**Comment by MohammadYounes** [comment]
In case of four-value syntax, functions are already flipped, for example:

* Input
  ```css
  body {
    padding:
      env(safe-area-inset-top, 20px)
      env(safe-area-inset-right, 20px)
      env(safe-area-inset-bottom, 20px)
      env(SAFE-AREA-INSET-LEFT, 50px)
    ;
  }
  ```
* Output
  ```css
  body {
    padding:
      env(safe-area-inset-top, 20px)
      env(SAFE-AREA-INSET-LEFT, 50px)
      env(safe-area-inset-bottom, 20px)
      env(safe-area-inset-right, 20px)
    ;
  }
  ```

In case of single value, most likely the declaration is flipped, for example:

* Input 
  ```css
  body {
   margin-left: env(safe-area-inset-left, 20px);
  }
  ```
* Output
  ```css
  body {
   margin-right: env(safe-area-inset-left, 20px);
  }
  ```

In case it was neither, users can explicitly specify the needed output, for example:

* Input
  ```css
  body {
   margin-top: /*rtl:env(safe-area-inset-left, 20px)*/env(safe-area-inset-right, 20px);
  }
  ```

* Output
  ```css
  body {
   margin-top: env(safe-area-inset-left, 20px);
  }
  ```

Based on the above, Where do you expect these to be flipped ?

**Comment by nex3** [comment]
I'd expect it to be flipped in both the first and second examples. I'd expect the outputs to be, respectively:

```css
body {
  padding:
    env(safe-area-inset-top, 20px)
    env(SAFE-AREA-INSET-RIGHT, 50px)
    env(safe-area-inset-bottom, 20px)
    env(safe-area-inset-left, 20px)
  ;
}
```

and

```css
body {
 margin-right: env(safe-area-inset-right, 20px);
}
```

Otherwise, if the device has asymmetrical safe areas, the padding/margin is no longer correctly ensuring that the content is within them.
