### ISSUE TITLE
The background-position declarations are flipped differently on version v4.0.0

### ISSUE THREAD

**Issue by elchininet** [MohammadYounes/rtlcss#298]
I tried the last version and I‘ve noticed this change:

### Input

```css
.test {
    background-position: 10px 20px;
}
```

### Output

```css
.test {
    background-position: right 10px top 20px;
}
```

https://runkit.com/embed/g3d996pobcue

It doesn‘t matter if I use the `useCalc` option, [the result is the same](https://runkit.com/embed/xypt265v0q62).

Is this on purpose?
