### ISSUE TITLE
Don't process data URLs

### ISSUE THREAD

**Issue by nex3** [MohammadYounes/rtlcss#309]
Currently if you enable the `processUrls` option, RTLCSS will apply its string map even to `data:` URLs. This will typically corrupt the URL contents, especially for base64-encoded URLs (which contain the text `ltr` or `rtl` reasonably often). Here's an example:

```css
/*rtl:options:{
  "stringMap": [
    {
      "name"    : "ltr-rtl",
      "priority": 100,
      "search"  : ["ltr"],
      "replace" : ["rtl"],
      "options" :	{
          "scope" : "url",
          "ignoreCase" : true
        }
    }
  ],
  "processUrls": true
}*/
.example {
   background: url(data:image/svg+xml;base64,ltr)
}
```
