### ISSUE TITLE
What features do you want to see in RTLCSS 2?

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#32]
Planning RTLCSS 2, Your input is very much appreciated!

**Comment by eneepo** [comment]
So far it has been flawless for me, I don't know what can be missed!!!
Thanks a million for the awesome work.

**Comment by MohammadYounes** [comment]
@eneepo You're welcome :smile:

**Comment by brianhadaway** [comment]
I'd like the ability to surround a set of declarations with a directive to prevent rtl conversion. The specific use case I have in mind is when I use SCSS and import an rtl-specific partial I could use this new directive to prevent the conversion of the rtl-specific styles while still converting my base styles. For example:

_grid-rtl.scss
```css
.col {
    text-align: right;
}
.row {
    margin-right: 20px;
}
```
_base.scss
```css
.myclass {
    text-align: left;
    border-left: 10px solid red;
}
```
_main.scss
```css
/*rtl:ignoreblock:start*/
@import _grid-rtl.scss;
/*rtl:ignoreblock:end*/

@import _base.scss;
```

After SASS and rtlcss run, output:
```css
/* from _grid-rtl.scss */
.col {
    text-align: right;
}
.row {
    margin-right: 20px;
}

/* from _base.scss */
.myclass {
    text-align: right;
    border-right: 10px solid red;
}
```

It was possible for me to work around this issue by restructuring files and using concat after rtlcss. It might be too much of an edge case for you to consider as a feature but it would be very convenient in much cleaner than my hack.

**Comment by MohammadYounes** [comment]
@brianhadaway  I created a separate [issue](https://github.com/MohammadYounes/rtlcss/issues/39) for this.

Thanks.

**Comment by gasolin** [comment]
Mozilla is developing some new CSS syntax to solve LTR/RTL issue with the same specificity
https://wiki.mozilla.org/Gaia/CSS_Guidelines#Direction_.28RTL.2FLTR_and_BiDi.29

It will be helpful to let developer write in new CSS syntax and interpret those syntax to current compatible syntax, so developer could get benefit from new CSS and keep the compatiblility.

**Comment by MohammadYounes** [comment]
@gasolin This tool is aimed at generating the RTL version of your current LTR CSS. 

Supporting such syntax requires a different tool, as the input CSS need to be converted to both LTR and RTL counterparts.

Thanks!

**Comment by jawadsahil** [comment]
Thanks for awesome work...

It is somehow related to @brianhadaway suggestion (or may be something different)... but there should be some conditional blocks. e.g.

/*font for rtl version of site*/
/*! if rtl 
@import ("google-noto-nastaleeq.css");
endif */

/*font for ltr version of site*/
/*! if not rtl */
@import ("google-noto-sans.css");
/*! endif */

so when RTLing the css, the 2nd block should be "Deleted"... and first block will be kept (and also uncommented) . And by default, the first block is already in comments, so it will be ignored in original ltr css.

**Comment by MohammadYounes** [comment]
@jawadsahil Good idea! As to keep this aligned with directives, may be something like:

* `raw` directive, which outputs what ever inside the comment
```css
/*font for rtl version of site*/
/*!rtl:raw:
@import ("google-noto-nastaleeq.css");
*/
```

* `omit` directive, which removes what ever inside the start and end:
```css
/*!rtl:omit:start*/
/* font for ltr version of site */
@import ("google-noto-sans.css");
/*!rtl:omit:end*/
```

Thanks!

**Comment by MohammadYounes** [comment]
Good news everyone,  RTLCSS 2.0 is almost ready!!

The [new version](https://github.com/MohammadYounes/rtlcss/tree/2.x) now supports more directives:

* **Control Directives**
  - Ignore
  - Rename
  - Raw
  - Remove
  - Options

* **Value Direcrtives**
  - Ignore
  - Replace
  - Insert
  - Append
  - Prepend

Control Directives comes with built-in support for block-style: 
```CSS
.my-class{
    margin-left: 15px;
    /*rtl:begin:ignore*/
    left: 20px;
    padding: 20px 10px 5px 2px;
   /*rtl:end:ignore*/
}
```


Moreover, the new API supports [plugins](https://github.com/MohammadYounes/rtlcss/blob/2.x/PLUGINS.md), Add more functionality to RTLCSS, or even change it's entire behavior.


Still, I need to perform a couple of reviews before public release (especially the documentation). 

Your feedback is highly appreciated!
