### ISSUE TITLE
Can't handle CSS style without semicolon

### ISSUE THREAD

**Issue by ok-jojo** [MohammadYounes/rtlcss#335]
Problem:
<img width="1041" alt="image" src="https://github.com/MohammadYounes/rtlcss/assets/133937909/2c5f5c93-495a-47cd-887a-5528066b1340">

Expect:
```css
.styles_cornerTopRight__efQwy{
    top:-5px;
    right:-5px
}
.styles_cornerBottomRight__IE1uZ{
    right:-5px;
    bottom:-5px
}
```
