### ISSUE TITLE
Auto-generate RTL styles in same stylesheet

### ISSUE THREAD

**Issue by cvan** [MohammadYounes/rtlcss#34]
Awesome project here! At Mozilla, we've been writing RTL styles by hand for years for all our fully localised sites. It's great to now have a tool that can auto-generate styles from LTR stylesheets (though, it'd be great it RTL stylesheets could be generated from LTR stylesheets).

Instead of having to conditionally load in RTL stylesheets, we treat RTL languages as first-class citizens and actually include `[dir=rtl]` for only RTL style overrides. Here's an example lifted from the [Firefox Marketplace](https://marketplace.firefox.com/?lang=ar) [CSS](https://marketplace.cdn.mozilla.net/media/fireplace/css/include.css?b=1436293462188):

```css
.category-header-icon {
  display: inline-block;
  margin-left: 6px;
}

[dir=rtl] .category-header-icon {
  margin-left: 0;
  margin-right: 6px;
}
```

rtlcss is awesome, but would it be possible to, instead of generating a separate RTL stylesheet, to auto-generate the RTL in the same stylesheet? Here are two suggested sample uses I can think of:

### input
```css
.category-header-icon {
  display: inline-block;
  margin-left: 6px;
}
```

### output
```css
[dir=rtl] .category-header-icon {
  margin-left: 0;
  margin-right: 6px;
}
```

## target LTR and RTL separately

When the direction style needs to be different, you can just target `[dir]`.

### input
```css
[dir=ltr] .category-header-icon {
  display: inline-block;
  margin-left: 6px;
}
```

### output
```css
[dir=rtl] .category-header-icon {
  display: inline-block;
  margin-right: 6px;
}
```

Thanks!
