### ISSUE TITLE
Wrong result when dealing with background with hex color with opacity (eg. "background: background: #00000080")

### ISSUE THREAD

**Issue by jieweizheng** [MohammadYounes/rtlcss#341]
This issue can be reproduce in the [playground](https://rtlcss.com/playground/#)
input:
```css
a. {
    background: #00000080;
}
```

expecting:
```css
a. {
    background: #00000080;
}
```

but result is:
```css
a. {
    background: #000000right 80 top 50%;
}
```
