### ISSUE TITLE
rtlcss is not working when there is a ignore comment `/*rtl:ignore*/` on an empty selector

### ISSUE THREAD

**Issue by kongweian1** [MohammadYounes/rtlcss#350]
## Problem

ignore comment `/*rtl:ignore*/` on an empty selector (`.first-selector`), then everything is broken.

example code
```css
/* rtl:ignore */
.first-selector {
}

.second-selector {
  padding-right: 6%;
}

.third-selector {
  padding-right: 6%;
}

.fourth-selector {
  padding-right: 6%;
}
```

try it in [playground](https://rtlcss.com/playground/#)

fail case
![Image](https://github.com/user-attachments/assets/60606bbf-aa1f-48c1-8909-d1c5f5180084)
