### ISSUE TITLE
Feature: Ability to ignore a set of rules

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#39]
Add the ability to surround a set of rules  with a directive to prevent rtl conversion.([details](https://github.com/MohammadYounes/rtlcss/issues/32#issuecomment-132347407))

**Comment by MohammadYounes** [comment]
@brianhadaway Thinking of a shorter directive name, how about:
```css
/*rtl:skip*/
@import _grid-rtl.scss;
/*rtl:resume*/
```
instead of 
```css
/*rtl:ignoreblock:start*/
@import _grid-rtl.scss;
/*rtl:ignoreblock:end*/
```
?

**Comment by brianhadaway** [comment]
@MohammadYounes - that makes sense to me.

**Comment by betaorbust** [comment]
I've run into this exact same thing (came here from the discussion topic) and I would like to +:100: to this idea.

Because of the nested nature of LESS/SASS/etc. and the ability to mix in, or inherit values, having a start and stop directive would be WONDERFUL.

Example:

Problem:
```LESS
/*rtl:ignore*/    // Trying to ignore this whole block
.myMixin(){
    left: 20px;
    padding: 20px 10px 5px 2px;
}
.my-class{
    margin-left: 15px;
    .my-mixin();
}


// Compiles after LESS to
.my-class{
    margin-left: 15px;
    left: 20px;
    padding: 20px 10px 5px 2px;
}

// And our ignore has been dropped :*(
```

With a start/stop we could use mixins:

```LESS
.myMixin(){
    /*rtl:pause*/
    left: 20px;
    padding: 20px 10px 5px 2px;
    /*rtl:resume*/
}
.my-class{
    margin-left: 15px;
    .my-mixin();
}


// Compiles after LESS to
.my-class{
    margin-left: 15px;
    /*rtl:pause*/
    left: 20px;
    padding: 20px 10px 5px 2px;
    /*rtl:resume*/
}

// Yay! This will work!
```

Very minor note: I think `pause` and `resume` are slightly better than `skip` and `resume` because `skip` isn't clear if it just skips the following line or if it's an overall parsing directive, whereas `pause` definitely conveys that rtl will not be running until something else happens.

**Comment by MohammadYounes** [comment]
The mixin case is different, where the number of declarations is usually limited:

```LESS
.myMixin(){
    left: 20px/*rtl:ignore*/;
    padding: 20px 10px 5px 2px/*rtl:ignore*/;
}
.my-class{
    margin-left: 15px;
    .my-mixin();
}


// Compiles after LESS to
.my-class{
    margin-left: 15px;
    left: 20px/*rtl:ignore*/;
    padding: 20px 10px 5px 2px/*rtl:ignore*/;
}

// Yay! This will work!
```

I believe v2 will be delayed and I might release this in 1.7! How about `begin-ignore` and `end-ignore` to eliminate any confusion ?

**Comment by betaorbust** [comment]
I picked pause/resume because it wouldn't be confused with the rtl:ignore directive (no shared words === different use case), but I'm not married to it.

> There are only two hard problems in Computer Science: cache invalidation, naming things, and off-by-one errors.

On the mixin front: you can totally do individual ignores (that's what I'm doing now) but we have quite a few mixins that are for things like building icons, where there are nested classes etc, and having a stop/start directive just makes it much easier to read and maintain.

Thanks for all your great work on RTLCSS!

**Comment by MohammadYounes** [comment]
I got your point, my concern is how to fit this into the current framework as Declaration level directives are placed any where inside the declaration value. 

It'll requires a new type of directives that are placed inside rules and before declarations (this will be considered in v2).  

Thanks!

**Comment by betaorbust** [comment]
:+1:

**Comment by MohammadYounes** [comment]
The new syntax will be using `begin`/`end` blocks for all control directives:

```css
/*rtl:begin:ignore*/
.class-1 {
 ...
}

.class-2 {
 ...
}
/*rtl:end:ignore*/

.class-3 {
    margin-left: 15px;
    /*rtl:begin:ignore*/
    left: 20px;
    padding: 20px 10px 5px 2px;
   /*rtl:end:ignore*/
}
```
