### ISSUE TITLE
Semantic UI rtl build

### ISSUE THREAD

**Issue by TeodorKolev** [MohammadYounes/rtlcss#42]
Hi there, I have found that popup in Semantic UI which use rtl not working. Is that issue in rtlcss or in Semantic UI? 

Thanks

**Comment by MohammadYounes** [comment]
Hi,

Are you using the RTL build ? Can you provide an online sample ?

Thanks!

**Comment by TeodorKolev** [comment]
10x for the quick response. I have made a rtl build and the result is same as here:
 https://github.com/Semantic-Org/Semantic-UI/issues/2652

**Comment by MohammadYounes** [comment]
It would be great if you could provide an online sample.

**Comment by TeodorKolev** [comment]
Sure:
http://jsfiddle.net/6e2pwznm/

**Comment by MohammadYounes** [comment]
Thanks! I'll check it and get back to you.

**Comment by MohammadYounes** [comment]
This was a nasty one! due to the change of popup classes structure things got double flipped :disappointed: 

Include the following CSS after `semantic.rtl.css` - this a temporary fix till I commit the changes to semantic.

```css
.ui.top.left.popup:before {
  left: 1em;
  right: auto;
}
.ui.top.right.popup:before {
  right: 1em;
  left: auto;
}
.ui.right.center.popup:before {
  left: -0.325em;
  right: auto;
  box-shadow:  -1px -1px 0px 0px #bababc ;
}
.ui.left.center.popup:before {
  right: -0.325em;
  left: auto;
  box-shadow:  1px 1px 0px 0px #bababc ;
}
.ui.bottom.left.popup:before {
  left: 1em ;
  right: auto ;
}
.ui.bottom.right.popup:before {
  right: 1em ;
  left: auto ;
}
```

Thanks
