### ISSUE TITLE
Feature: Ability to remove rule(s) or declaration(s)

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#49]
Unlike ignore, a new directive to remove the rules from RTL version.

**Comment by MohammadYounes** [comment]
The new directive syntax is as follows:

```CSS
/*rtl:remove*/
.my-class{
  ....
}

/*rtl:begin:remove*/
.my-class-1{
  ....
}

.my-class-2{
  ....
}
/*rtl:end:remove*/

.my-class{
  /*rtl:remove*/
  direction: rtl;
  text-align: right;
  padding: 10px;
}


.my-class{
  /*rtl:begin:remove*/
  direction: rtl;
  text-align: right;
  /*rtl:end:remove*/
  padding: 10px;
}
```
