### ISSUE TITLE
Feature: Ability to add rule(s) or declaration(s)

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#50]
Adds new rules or declarations to the RTL version.

**Comment by MohammadYounes** [comment]
The new syntax is as follows:

```CSS
/*rtl:raw: div { left:10px;text-align:right;}*/ a {display:block;}

div { /*rtl:raw: font-family: "Droid Kufi Arabic";*/ left:10px;text-align:right;}
```

which outputs:

```CSS
div {left:10px;text-align:right;} a {display:block;}

div { font-family:"Droid Kufi Arabic"; right:10px;text-align:left;}
```
