### ISSUE TITLE
Feature: Ability to set options inside CSS 

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#54]
The new options directives, allows settings RTLCSS options inside the CSS document. With support for nested options overrides.

The new syntax will be as follows:

```CSS
/*rtl:begin:options:
{
  "autoRename": true,
  "stringMap":[
    {
      "name"    : "prev-next",
      "search"  : ["prev", "Prev", "PREV"],
      "replace" : ["next", "Next", "NEXT"],
      "options" : {"ignoreCase":false}
    }]
}
*/

.demo-prev, .demo-Prev, .demo-PREV { content: 'p'; }
.demo-next, .demo-Next, .demo-NEXT { content: 'n'; }

/*rtl:end:options*/
```
