### ISSUE TITLE
I guess something is wrong here!

### ISSUE THREAD

**Issue by OsamaAbbas** [MohammadYounes/rtlcss#57]
Could you please check this behaviour?

```javascript
require("rtlcss").process(`.text-left {
  text-align: left;
}`, {
  autoRename: false
});
// output: '.text-left { text-align: right; }'
```

```javascript
require("rtlcss").process(`.text-left {
  text-align: left;
}`, {
  autoRename: true
});
// output: '.text-left { text-align: right; }'
```

How could I get it to rename them both or ignore them both?

**Comment by OsamaAbbas** [comment]
Bootstrap has many rules like that previous example.

```css
@media (min-width: 768px) {
  .navbar-left {
    float: left !important;
  }
  .navbar-right {
    float: right !important;
    margin-right: -15px;
  }
  .navbar-right ~ .navbar-right {
    margin-right: 0;
  }
}
```

After conversion:

```css
@media (min-width: 768px) {
  .navbar-left {
    float: right !important;
  }
  .navbar-right {
    float: left !important;
    margin-left: -15px;
  }
  .navbar-right ~ .navbar-right {
    margin-left: 0;
  }
}
```
