### ISSUE TITLE
RTLCSS results in invalid property transformation

### ISSUE THREAD

**Issue by svieira** [MohammadYounes/rtlcss#68]
```shell
npm ls | grep rtlcss
rtlcss@2.0.2
```

### Before

```css
.some-class {
  cursor: ew-resize;
}
```

### After

```css
.some-class {
  cursor: we-resize;
}
```

### The problem

`we-resize` is [not a valid value](https://www.w3.org/TR/css-ui-3/#cursor) for `cursor`.
