### ISSUE TITLE
Having anything in RTL files, but not having anything to the LTR file

### ISSUE THREAD

**Issue by NabiKAZ** [MohammadYounes/rtlcss#73]
Hi,

I have a `SCSS` file `iefix.scss`:
```
#main-search {
    border-radius: 25px 0 0 25px;
    border: $myborder;
}
```
This compile to `iefix-ltr.css` with `phpstorm` watcher, and then compile to `iefix-rtl.css` with your `RTLCSS` project.

I need to have `iefix-ltr.css` file nothing content it! or just a comment:
`/* nothing here! */`

But I need to have `iefix-rtl.css` exactly compiled content of `iefix.scss` file:
```
#main-search {
    border-radius: 25px 0 0 25px;
    border: 0;
}
```

How can I setup `RTLCSS ` for this workflow?

Thanks.

**Comment by MohammadYounes** [comment]
`RTLCSS` has no control over `SCSS` compilation. However, you can still do the following:

**iefix.scss**
```scss
$myborder: 0;
/*rtl:raw:
#main-search {
    border-radius: 25px 0 0 25px;
    border: #{$myborder};
}
*/
```

**iefix-ltr.css**:
```css
/*rtl:raw:
#main-search {
    border-radius: 25px 0 0 25px;
    border: 0;
}
*/
```
**iefix-rtl.css**:
```css
#main-search {
 border-radius: 25px 0 0 25px;
 border: 0
}
```

Hope this helps!
