### ISSUE TITLE
add "auto" values after replacing position declarations

### ISSUE THREAD

**Issue by amitkeret** [MohammadYounes/rtlcss#76]
Since style-rtl.css in parsed in *addition* to the source style.css files, overwriting left/right declarations is not enough.

Consider this:
```css
/* style.css */
.float-absolute {
  left: 0;
}

/* style-rtl.css */
.float-absolute {
  right: 0;
  /* Should automatically add: */
  left: auto;
}
```

**Comment by MohammadYounes** [comment]
The RTL version of:
```css
/* style.css */
.float-absolute {
  left: 0;
}
```
Should be:
```css
/* style.css */
.float-absolute {
  right: 0;
}
```

As this tool is intended to provide complete automation, it generates a complete RTL style sheet.

See [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)
