### ISSUE TITLE
stringMap not working :cry:

### ISSUE THREAD

**Issue by sidati** [MohammadYounes/rtlcss#80]
Assalmo Alykum @MohammadYounes,
I can get why "stringMap" aint working :cry: !!! 
```
rtlcss: {
	nemico: {
		src: 'assets/fonts/icons/nemico.css',
		dest: 'assets/fonts/icons/nemico-rtl.css',
		options: {
			opts: {
				stringMap: [{
					priority: 0,
					name: "icon-1",
					search: 'login',
					replace: 'logout',
					options: {
						scope: '*',
						ignoreCase: false
					}
				}]
			}
		}
	}
}
```

**Comment by MohammadYounes** [comment]
You need to enable `autoRename`

**Comment by sidati** [comment]
@MohammadYounes Still not working

**Comment by MohammadYounes** [comment]
@sidati provide me with a CSS sample, including the login/logout selectors.

**Comment by sidati** [comment]
Here is
```
.nemico_logout:before, .nemico_logout-a:after { content: '\e84c'; }
.nemico_login:before, .nemico_login-a:after { content: '\e84d'; }
```

**Comment by sidati** [comment]
@MohammadYounes Any ideas ??

**Comment by MohammadYounes** [comment]
Yes, your naming convention requires [`greedy`](http://rtlcss.com/learn/usage-guide/string-map/#map-options) to be on too.

**Comment by MohammadYounes** [comment]
Try the following in the [playground](http://rtlcss.com/playground):

```css
/*rtl:options:
{
  "autoRename": true,
  "stringMap":[
     {
         "priority": 0,
         "name": "icon-1",
         "search": "login",
         "replace": "logout",
         "options": {
             "scope": "*",
             "ignoreCase": false,
             "greedy": true
        }
     }
  ]
}
*/

.nemico_logout:before,
.nemico_logout-a:after {
  content: '\e84c';
}

.nemico_login:before,
.nemico_login-a:after {
  content: '\e84d';
}
```
