### ISSUE TITLE
Updating `node.value`

### ISSUE THREAD

**Issue by emilbayes** [MohammadYounes/rtlcss#85]
When using `rtlcss` as a processing step before other PostCSS plugin's I'm having issues with them picking up on changes made by `rtlcss` because of the way it updates the AST.

Consider the following css:

```css
:root {
  --font-family-noto: 'Noto Sans', sans-serif /*rtl:prepend:'Noto Kufi Arabic', */;
}

body {
  font-family: var(--font-family-noto);
}
```

Processing:

```sh
postcss --use rtlcss --use postcss-custom-properties example.css
```

Output:
```css
body {
  font-family: 'Noto Sans', sans-serif ;
}
```

This is due to `rtlcss` modifying the `raw.value.raw` css, while `postcss-custom-properties` reads the `.value`. I don't know which is more correct, I've just noted that lots of other PostCSS plugins mutate `decl.value`.

I can do a PR, but all it really takes is to append `node.value = node.raws.value.raw` after [`lib/rtlcss.js#L106`](https://github.com/MohammadYounes/rtlcss/blob/46688c683856e1349ed9603de24b54bd60624d87/lib/rtlcss.js#L106)
