### ISSUE TITLE
Issue with CSS variable `--brightest`

### ISSUE THREAD

**Issue by emilbayes** [MohammadYounes/rtlcss#86]
Consider the following CSS:

```css
:root {
  --brightest: #fff;
}

body {
  background: var(--brightest);
}
```

The transformed CSS:

```css
:root {
  --bleftest: #fff;
}

body {
  background: var(--brightest);
}
```

I guess this is due to the naive algorithm used for [replacing right/left](https://github.com/MohammadYounes/rtlcss/blob/222a98c3b5fcb75edb77167ce09b2a61c9fbd0ae/lib/plugin.js#L180-L184)?
Does this require adding support for CSS variables? A solution might be to filter `--*` since that is the prefix used for a lot of the proposed extensions to CSS.

**Comment by MohammadYounes** [comment]
For the time being, you can use [ignore directive](http://rtlcss.com/learn/usage-guide/control-directives/#ignore) or add a [custom plugin](http://rtlcss.com/learn/extending-rtlcss/writing-a-plugin/) to ignore these variables.

```js
{
  'name': 'Skip variables',
  'priority': 1,
  'directives': { 'control': {}, 'value': [] },
  'processors': [
     {
       'name': '--',
       'expr': /^--/im,
       'action': function (prop, value, context) {
         return { 'prop': prop, 'value': value }
       }
     }
  ]
}
```
Demo: https://runkit.com/mky/rtlcss---custom-plugin-to-prevent-processing-variables

**Comment by gusbemacbe** [comment]
How do I apply it to your online RTL?

**Comment by MohammadYounes** [comment]
@gusbemacbe For the time being, Add it as a [comment](http://rtlcss.com/learn/usage-guide/control-directives/#config) at the beginning of the provided CSS:

```css
/*rtl:config:{
    "plugins":[
        {
            "name": "Skip variables",
            "priority": 1,
            "directives": { "control": {}, "value": [] },
            "processors": [
                {
                    "name": "--",
                    "expr": /^--/im,
                    "action": function (prop, value, context) {
                        return { "prop": prop, "value": value }
                    }
                }
            ]
        }
    ]
}*/
:root {
  --brightest: #fff;
}
```
