### ISSUE TITLE
How to add some properties for rtl only?

### ISSUE THREAD

**Issue by MoshiraRefaat** [MohammadYounes/rtlcss#97]
I have a background image that should be reversed horizontally in Arabic.
before using RTLCSS framework I added the code below in the rtl css file to reverse it. Now how I can add this code to the rtl only.
   `transform:scale(-1,1);
    -webkit-transform:scale(-1,1);
    -moz-transform:scale(-1,1);`

**Comment by MohammadYounes** [comment]
You can use [`raw`](http://rtlcss.com/learn/usage-guide/control-directives/#raw) control directive or [`replace`](http://rtlcss.com/learn/usage-guide/value-directives/#replace) value directive.

Example:
```css
.example {
  /*rtl:raw:
    transform:scale(-1,1);
  */;
}
/* OR */
.example {
  transform:scale(1,1) /*rtl:scale(-1,1)*/;
 }
```
will produce

```css
.example {
  transform:scale(-1,1);
}
```
